### ISSUE TITLE
sample_sim.txt wrong content

### ISSUE THREAD

**Issue by darked89** [LazyShion/ScaleAP#1]
Hello,

I attempted to run 
```
./convert -i sample_graph.txt -o sample_graph.bin
```

since in the repository there is just one file pair with matching suffixes I did:

```
./convert -i sample_sim.txt -o sample_sim.bin
```  

Got a 4 byte output. Creating a new file from the example in the README.md:
```
4	// # of objects
-0.11	// sim(1,1)
-0.12	// sim(1,2)
-0.13	// sim(1,3)
-0.14	// sim(1,4)
-0.21	// sim(2,1)
-0.22	// sim(2,2)
-0.23	// sim(2,3)
-0.24	// sim(2,4)
-0.31	// sim(3,1)
-0.32	// sim(3,2)
-0.33	// sim(3,3)
-0.34	// sim(3,4)
-0.41	// sim(4,1)
-0.42	// sim(4,2)
-0.43	// sim(4,3)
-0.44	// sim(4,4)
```

Gave me 132 byles long .bin file but withdifferent md5sum than ```sample_graph.bin``` and rather bad content (hexdump): 

```
0000000 0004 0000 0000 0000 0000 0000 0000 0000
0000010 0000 0000 0000 0000 0000 0000 0000 0000
*
0000084
```

Would it be possible to get not just a proper micro-example but a small set of input files for testing? Or a links from where one can get them?

Hope it helps

Darek Kedra

**Comment by LazyShion** [comment]
Hi, 

On my environments (MacOS Monterey, CentOS Stream 8, etc.), `sample_sim.txt` works correctly without any modifications. `./convert -i sample_sim.txt -o sample_sim.bin` successfully outputs 132 bytes long .bin file, and `./ScaleAP` works on the .bin file. 

I guess there exist some installation failure (e.g., file format, compile settings, missing libraries, etc.) on your environment. If you attempt to reproduce `sample_sim.txt` by yourself, please remove the supplemental substrings from each line (e.g.,`// # of objects`, `// sim(1,1)`, `// sim(1,2)`, ...) Those substrings might be some troubles in `./convert`.

> Would it be possible to get not just a proper micro-example but a small set of input files for testing? Or a links from where one can get them?

I'll do it if I have enough time for this.

Best regards,

Hiroaki

**Comment by darked89** [comment]
Hello,

After a fresh: 
```
git clone https://github.com/LazyShion/ScaleAP.git
make clean 
make -j 8
mv sample_sim.bin sample_sim.bin.SAFE
./convert -i sample_sim.txt -o sample_sim.bin
```

everything works as it should:

```
958746aaeb37b32cbafe47388a5023c0  sample_sim.bin
958746aaeb37b32cbafe47388a5023c0  sample_sim.bin.SAFE
f67988110557ea0e49639278d64db807  sample_sim.txt
```

So apart from README.md input example it was probably a false alarm. Sorry for this.

BTW, I am on Ubuntu 20.04 with gcc 9.3.0

Best,

DK
