### ISSUE TITLE
possible mismatch of object numbering schemes (README vs ScaleAP output)

### ISSUE THREAD

**Issue by darked89** [LazyShion/ScaleAP#2]
Hello,

in section: https://github.com/LazyShion/ScaleAP#input-file

the object numbering follows nubering of objects starting at 1: sim(1,3)

in the last section: https://github.com/LazyShion/ScaleAP#example
as well as in the output of the command there is:

```
./ScaleAP -i sample_sim.bin -R -p 0.01
Object	Cluster
0	0
1	1
2	2
3	3
```

which is a starting at 0 (zero) object numbering scheme. Would it be possible to have just one object numbering standard for the inputs and output of the program?

Many thanks for your help in advance

Darek Kedra

**Comment by LazyShion** [comment]
Hi Darek,

Thank you for your feedback. In ScaleAP, the dataset should be starting at 0 object numbering scheme. I will correct Readme.md later.

Thank you,

Hiroaki
